//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextPad_.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class RecentFiles : global::System.Configuration.ApplicationSettingsBase {
        
        private static RecentFiles defaultInstance = ((RecentFiles)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RecentFiles())));
        
        public static RecentFiles Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string RecentFile0 {
            get {
                return ((string)(this["RecentFile0"]));
            }
            set {
                this["RecentFile0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string RecentFile1 {
            get {
                return ((string)(this["RecentFile1"]));
            }
            set {
                this["RecentFile1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string RecentFile2 {
            get {
                return ((string)(this["RecentFile2"]));
            }
            set {
                this["RecentFile2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string RecentFile3 {
            get {
                return ((string)(this["RecentFile3"]));
            }
            set {
                this["RecentFile3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string RecentFile4 {
            get {
                return ((string)(this["RecentFile4"]));
            }
            set {
                this["RecentFile4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string RecentFile5 {
            get {
                return ((string)(this["RecentFile5"]));
            }
            set {
                this["RecentFile5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string RecentFile6 {
            get {
                return ((string)(this["RecentFile6"]));
            }
            set {
                this["RecentFile6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string RecentFile7 {
            get {
                return ((string)(this["RecentFile7"]));
            }
            set {
                this["RecentFile7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string RecentFile8 {
            get {
                return ((string)(this["RecentFile8"]));
            }
            set {
                this["RecentFile8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string RecentFile9 {
            get {
                return ((string)(this["RecentFile9"]));
            }
            set {
                this["RecentFile9"] = value;
            }
        }
    }
}
