//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextPad_.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class RecentFiles : global::System.Configuration.ApplicationSettingsBase {
        
        private static RecentFiles defaultInstance = ((RecentFiles)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RecentFiles())));
        
        public static RecentFiles Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string element0 {
            get {
                return ((string)(this["element0"]));
            }
            set {
                this["element0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string element1 {
            get {
                return ((string)(this["element1"]));
            }
            set {
                this["element1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string element2 {
            get {
                return ((string)(this["element2"]));
            }
            set {
                this["element2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string element3 {
            get {
                return ((string)(this["element3"]));
            }
            set {
                this["element3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string element4 {
            get {
                return ((string)(this["element4"]));
            }
            set {
                this["element4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string element5 {
            get {
                return ((string)(this["element5"]));
            }
            set {
                this["element5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string element6 {
            get {
                return ((string)(this["element6"]));
            }
            set {
                this["element6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string element7 {
            get {
                return ((string)(this["element7"]));
            }
            set {
                this["element7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string element8 {
            get {
                return ((string)(this["element8"]));
            }
            set {
                this["element8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missing")]
        public string element9 {
            get {
                return ((string)(this["element9"]));
            }
            set {
                this["element9"] = value;
            }
        }
    }
}
