//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextPad_.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextPad_.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По вашему запросу ничего не нашлось..
        /// </summary>
        public static string LineNotFound {
            get {
                return ResourceManager.GetString("LineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось удалить элемент..
        /// </summary>
        public static string MSGErrorCantDeleteFile {
            get {
                return ResourceManager.GetString("MSGErrorCantDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не найден..
        /// </summary>
        public static string MSGErrorFileNotFound {
            get {
                return ResourceManager.GetString("MSGErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не открыто ни одной вкладки..
        /// </summary>
        public static string MSGErrorNoTabsOpen {
            get {
                return ResourceManager.GetString("MSGErrorNoTabsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать путь до интерпретатора Python..
        /// </summary>
        public static string MSGErrorPythonInterPath {
            get {
                return ResourceManager.GetString("MSGErrorPythonInterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при запуске сценария командной строки. Возможно, он неправильно сохранён или отсутствует файл C:\Windows\cmd.exe..
        /// </summary>
        public static string MSGErrorRunBatCmdFile {
            get {
                return ResourceManager.GetString("MSGErrorRunBatCmdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при запуске Python программы..
        /// </summary>
        public static string MSGErrorRunPythonFile {
            get {
                return ResourceManager.GetString("MSGErrorRunPythonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при запуске файла сценария Visual Basic / JScript. Возможно, он неправильно сохранён или отсутствует программа Windows Based Host Script C:\Windows\System32\wscript.exe ..
        /// </summary>
        public static string MSGErrorRunVBSJSFile {
            get {
                return ResourceManager.GetString("MSGErrorRunVBSJSFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка. Проверьте подключение к интернету..
        /// </summary>
        public static string MSGErrorWhenCheckingInternet {
            get {
                return ResourceManager.GetString("MSGErrorWhenCheckingInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При открытии файла возникла ошибка.
        /// </summary>
        public static string MSGErrorWhenOpenFIle {
            get {
                return ResourceManager.GetString("MSGErrorWhenOpenFIle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно запустить пустой скрипт.
        /// </summary>
        public static string MSGErrorWhenRunningEmptyScript {
            get {
                return ResourceManager.GetString("MSGErrorWhenRunningEmptyScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При сохранении файла возникла ошибка.
        /// </summary>
        public static string MSGErrorWhenSaveFile {
            get {
                return ResourceManager.GetString("MSGErrorWhenSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить элемент в корзину?.
        /// </summary>
        public static string MSGQestionMoveFileToTrash {
            get {
                return ResourceManager.GetString("MSGQestionMoveFileToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить текст в файл.
        /// </summary>
        public static string MSGQuestionSaveFile {
            get {
                return ResourceManager.GetString("MSGQuestionSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый документ.
        /// </summary>
        public static string newDocumentTitle {
            get {
                return ResourceManager.GetString("newDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текстовые документы (*.txt)|*.txt|Файл TextPad*.tpf)|*.tpf |Файл сценария VBS (*.vbs)|*.vbs|Пакетный файл DOS (*.bat)|*.bat|Пакетный файл Windows (*.cmd)|*.cmd|Сценарий PowerShell (*.ps1)|*.ps1|Python files (*.py)|*.py|Web страница (*.html)|*.html|Cascade Style Sheets (*.css)|*.css|JavaScript, JScript (*.js)|*.js|INI конфигурация (*.ini)|*.ini|XML конфигурация (*.xml)|*.xml|Все файлы (*.*)|*.*.
        /// </summary>
        public static string openFileDialogFilter {
            get {
                return ResourceManager.GetString("openFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка наличия обновлений... .
        /// </summary>
        public static string PROGRAMStatusCheckForUpdates {
            get {
                return ResourceManager.GetString("PROGRAMStatusCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка... .
        /// </summary>
        public static string PROGRAMStatusLoading {
            get {
                return ResourceManager.GetString("PROGRAMStatusLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готово .
        /// </summary>
        public static string PROGRAMStatusReady {
            get {
                return ResourceManager.GetString("PROGRAMStatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идёт обновление... .
        /// </summary>
        public static string PROGRAMStatusUpdating {
            get {
                return ResourceManager.GetString("PROGRAMStatusUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текстовые документы (*.txt)|*.txt|Файл TextPad*.tpf)|*.tpf |Файл сценария VBS (*.vbs)|*.vbs|Пакетный файл DOS (*.bat)|*.bat|Пакетный файл Windows (*.cmd)|*.cmd|Сценарий PowerShell (*.ps1)|*.ps1|Python files (*.py)|*.py|Web страница (*.html)|*.html|Cascade Style Sheets (*.css)|*.css|JavaScript, JScript (*.js)|*.js|INI конфигурация (*.ini)|*.ini|XML конфигурация (*.xml)|*.xml|Все файлы (*.*)|*.*.
        /// </summary>
        public static string saveFileDialogFilter {
            get {
                return ResourceManager.GetString("saveFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдено такого слова..
        /// </summary>
        public static string SearchUINoFoundWord {
            get {
                return ResourceManager.GetString("SearchUINoFoundWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для применения настроек перезапустите программу..
        /// </summary>
        public static string SettingsLangChange {
            get {
                return ResourceManager.GetString("SettingsLangChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная ошибка.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прервать установку обновления?.
        /// </summary>
        public static string UPDATERAbortUpdate {
            get {
                return ResourceManager.GetString("UPDATERAbortUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось проверить наличие обновлений. Проверьте подключение к интернету..
        /// </summary>
        public static string UPDATERErrorCantCheckUpdates {
            get {
                return ResourceManager.GetString("UPDATERErrorCantCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Непредвиденная ошибка..
        /// </summary>
        public static string UPDATERErrorUnexpectedError {
            get {
                return ResourceManager.GetString("UPDATERErrorUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас установлена последняя версия программы.
        /// </summary>
        public static string UPDATERInfoLatestVersion {
            get {
                return ResourceManager.GetString("UPDATERInfoLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступно обновление. Установить? Перед установкой обновления сохраните все данные в программе..
        /// </summary>
        public static string UPDATERInfoUpdateAvailable {
            get {
                return ResourceManager.GetString("UPDATERInfoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрытие программы....
        /// </summary>
        public static string UPDATERStatusUpdateClosingProgram {
            get {
                return ResourceManager.GetString("UPDATERStatusUpdateClosingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление старой версии....
        /// </summary>
        public static string UPDATERStatusUpdateDeleteOldVersion {
            get {
                return ResourceManager.GetString("UPDATERStatusUpdateDeleteOldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачивание и установка....
        /// </summary>
        public static string UPDATERStatusUpdateDownloadAndInstall {
            get {
                return ResourceManager.GetString("UPDATERStatusUpdateDownloadAndInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установщик обновлений.
        /// </summary>
        public static string UPDATERTitle {
            get {
                return ResourceManager.GetString("UPDATERTitle", resourceCulture);
            }
        }
    }
}
